### ISSUE TITLE
material effect label

### ISSUE THREAD

**Issue by Nachtpfoetchen** [Floorp-Projects/Floorp-Strings#3]
I am currently working on a German translation. There is a line that i don't understand:

`material-effect =
 .label = Allow Mica For Everyone to modify the browser design`

What is meant with Mica? Is it a name, or something? I am not sure how to translate that line. Also i wasn't able to find where the line is used in about:preferences

**Comment by creeper-0910** [comment]
https://learn.microsoft.com/en-us/windows/apps/design/style/mica

**Comment by surapunoyousei** [comment]
"Mica" is a name, that is a Window interface desgin, like Windows 11

**Comment by Nachtpfoetchen** [comment]
Ahh thank you, good to know :)
